### ISSUE TITLE
basic_masked_language_model.py输出结果总是"the"

### ISSUE THREAD

**Issue by DaiHaoguang3151** [MuQiuJun-AI/bert4pytorch#18]
```python
sentence = "北京[MASK]安门"
``` 

huggingface上下载的bert-base-uncased模型，预测的结果总是"the"，为什么

**Comment by Tongjilibo** [comment]
> ```python
> sentence = "北京[MASK]安门"
> ```
> 
> huggingface上下载的bert-base-uncased模型，预测的结果总是"the"，为什么

一个是使用中文建议使用bert-base-chinese, 你下载的是英文的，还有一个注意下权重是否需要转换

**Comment by DaiHaoguang3151** [comment]
已经解决了。谢谢
